custom.schedule.keyword.run: true

spring:
 thymeleaf:
  cache: false 
 h2:
   console:
     enabled: true
     path: /h2-console
 datasource:
   url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
   username: sa
   password: 
 jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   showSql: true
   hibernate:
    ddl-auto: create-drop
   generate-ddl: true
   show-sql: true
   database: h2
 redis:
   host: localhost
   password: 
   port: 6379

api:
 kakaosearch:
   host: https://dapi.kakao.com
   uri:
     keyword: /v2/local/search/keyword.json
   token: e212fb209dc745c6e7e874652663fda7
   authHeader: KakaoAK
 naversearch:
   host: https://openapi.naver.com
   uri:
     keyword: /v1/search/local.json
   clientid: eY7SiBFpNJcw80UORG4h
   clientsecret: T3y7R4QSJZ


logging:
 level:
   root: info